### ISSUE TITLE
Handling of non-initial falling accents

### ISSUE THREAD

**Issue by sveto** [Zabolekar/jezik#10]
Some words have variants with non-initial falling accent, even if it is not always welcomed by the standard(s).

compound words: пољопри̏вреда (along with -ѝ-); Југосла̏вија (along with -о̀)
new words with foreign elements: зафр̥ка̏нт (along with зафр̥̀кант)
interjections: хало̑  (along with ха̀ло̄)
Gen. Pl.: Македо̑на̄ца̄ (along with Макѐдо̄на̄ца̄)

In Garde-like notation, some special sign like "!" should be used. Hence, пољо!при̍вреда; зафр̥!ка̍нт, ха!ло̄̍ etc.

**Comment by Zabolekar** [comment]
Let's use ! in our notation:
- it won't be shifted weirdly in any font the user is likely to use
- it's easy to remember (! in Prolog prevents backtracking, ! in our notation will prevent the accent from being retracted)

It also means that we should be especially careful when handling our raw data. We will have to strip every word, especially interjections, of any final exclamation signs. But we wanted to do it anyway.

**Comment by Zabolekar** [comment]
Our `ungarde` function now is able to handle the ``!`-notation. Should work as long as there is at most one vowel between ! and the accent sign.

**Comment by sveto** [comment]
Our garde function is now able to put "!", too. So the problem is cured (hopefully).
