### ISSUE TITLE
Input (essential)

### ISSUE THREAD

**Issue by Zabolekar** [Zabolekar/jezik#21]
- [x] работа с разными рефлексами ятя на входе (по выбору пользователя)
- [x] работа с разными рефлексами ятя на выходе (по выбору пользователя)
- [x] ввод латиницей (определять автоматически)
- [x] вывод латиницей (по выбору пользователя)
- [x] кнопки с буквами `љ њ ђ ћ ј џ` для тех, у кого только украинская или русская раскладка (обдумать, как это сделать, чтобы не замусорить интерфейс)
- [x] аналогично `č ć đ š ž` для латиницы (но см. также #22 про ошишану латиницу)

**Comment by sveto** [comment]
Seems to be done.
