### ISSUE TITLE
Impossible forms

### ISSUE THREAD

**Issue by Zabolekar** [Zabolekar/jezik#3]
> Svetozar ЄЭ: надо будет ввести некоторые пометки в словаре, блокирующие некоторые формы у некоторых слов
> Svetozar ЄЭ: для глаголов это переходный/непереходный (у непереходного нет причастия) и совершенный/несовершенный/двувидовой (у совершенного нет имперфекта)
> Svetozar ЄЭ: (а аорист почему-то есть и Даничич его приводит)
> Svetozar ЄЭ: ну, можно сказать заплакать — заплаканный (потому что заплакать можно что-то), но нельзя сказать плакан(н)ый (потому что не бывает „я пла́чу своё лицо“)
> Svetozar ЄЭ: в-третьих таки да возвратность (можно её запхать к переходности третьим пунктом)
> Svetozar ЄЭ: ну хорошо, выплаканный, так можно много про что сказать, а не только про лицо
> Levune-shayn: в общем, я так понимаю ситуацию: такие формы мы можем образовать (причём всегда), но не можем нигде применить осмысленно, так?
> Svetozar ЄЭ: да
> Levune-shayn: т.е. их можно в принципе уже фильтровать на стадии вывода результата (ну там красить бледно-сереньким)
> Svetozar ЄЭ: да

**Comment by sveto** [comment]
Added long ago: _verb_form_is_possible(). Feel free to add other conditions!
