### ISSUE TITLE
Yat variants and different long yat accentuation

### ISSUE THREAD

**Issue by sveto** [Zabolekar/jezik#5]
e ~ је
е ~ и
е̄ ~ ије
е̄ ~ је̄
е̄ ~ ӣ

Also: 

ри̏јеч ~ ри̯је̑ч
вијѐнац ~ ви̯је́нац
по̏вијест ~ по̏ви̯је̄ст

All these correspondences between ekavian, two-syllable ijekavian and one-syllable jekavian pronunciations should be foreseen and supported.

Maybe a checkbox e/je/ije.

Also consider: words like повијест and тједан are ijekavian only.
Also: behaviour like белег ~ биљег.

**Comment by Zabolekar** [comment]
- [x] чекбокс
- [x] ије vs. и̯је 
- [x] про тједан лучше в комментарий

Прочее готово.

**Comment by Zabolekar** [comment]
Впрочем, пункт про чекбокс уже покрыт #21 .

**Comment by sveto** [comment]
Yat works.
